ceph_diagnostics_show: more verbose error when cct not set up
Signed-off-by: Mykola Golub <mykola.golub@clyso.com>

diff --git a/ceph_diagnostics_show/commands/cct b/ceph_diagnostics_show/commands/cct
--- a/ceph_diagnostics_show/commands/cct
+++ b/ceph_diagnostics_show/commands/cct
@@ -13,6 +13,7 @@ help() {
 
 cct() {
     if [ ! -d "${CLYSO_CCT_DIR}/venv" ]; then
+	echo "cannot find cct virtual environment ${CLYSO_FSA_DIR}/venv" >&2
 	echo "cct is not installed or CLYSO_CCT_DIR is not set correctly" >&2
 	exit 1
     fi
