ceph_diagnostics_show: make "asok" commands work
(for "incompatible" archives)

Signed-off-by: Mykola Golub <mykola.golub@clyso.com>

diff --git a/ceph_diagnostics_show/commands/mds b/ceph_diagnostics_show/commands/mds
--- a/ceph_diagnostics_show/commands/mds
+++ b/ceph_diagnostics_show/commands/mds
@@ -34,10 +34,10 @@ help() {
 
 asock_cmd() {
     local cmd=$1
-    local file="$(ls ${CEPH_DIAGNOSTICS_COLLECT_DIR}/fs_info-mds.${DAEMON_NAME}_${cmd} | head -1)"
+    local file="$(ls ${CEPH_DIAGNOSTICS_COLLECT_DIR}/fs_info-mds.${DAEMON_NAME}[-_]${cmd} | head -1)"
 
     if [ -z "${file}" ]; then
-	echo "failed to find fs_info-mds.${DAEMON_NAME}_${cmd} file in collect dir" >&2
+	echo "failed to find fs_info-mds.${DAEMON_NAME}-${cmd} file in collect dir" >&2
 	return 1
     fi
 
